[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[cursor.style]
blinking = "Off"
shape = "Beam"

[font]
# draw_bold_text_with_bright_colors = true
size = 13

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 10000
multiplier = 3

[window]
option_as_alt = "Both"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5
